# Generated by Django 3.1.4 on 2021-01-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_editprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
